version: "3.7"
services:
  haproxy:
    container_name: haproxy
    hostname: haproxy
    image: cellaresctmpcontainerregistry.azurecr.io/haproxy:2.9.3
    restart: unless-stopped
    ports:
      - 5673:5672
      - 15673:15672
    environment:
      TZ: America/Los_Angeles
    dns:
      - 172.22.0.100
      - 1.1.1.1
    volumes:
      - type: bind
        source: C:/CellShuttle/docker-volumes/haproxy/etc/
        target: /usr/local/etc/haproxy
    networks:
      shuttle-network:
        ipv4_address: 172.22.0.107
    healthcheck:
      test: exit 0
      interval: 10s
      timeout: 10s
      retries: 1
    logging:
      driver: json-file
      options:
        max-size: 15m
        max-file: "1"
    entrypoint: null
    depends_on:
      rabbitmq3:
        condition: service_healthy
  rabbitmq1:
    container_name: rabbitmq1
    hostname: rabbitmq1
    image: cellaresctmpcontainerregistry.azurecr.io/rabbitmq:3.12.12-management
    restart: unless-stopped
    ports:
      - 5673:5672
      - 15673:15672
    environment:
      TZ: America/Los_Angeles
      RABBITMQ_ERLANG_COOKIE: cellares-rabbitmq-cookie-shuttle
    dns:
      - 172.22.0.100
      - 1.1.1.1
    volumes:
      - type: bind
        source: C:/CellShuttle/docker-volumes/rabbitmq1/etc/
        target: /usr/local/etc/rabbitmq1
      - type: bind
        source: C:/CellShuttle/docker-volumes/rabbitmq1/data/
        target: /var/lib/rabbitmq/mnesia
      - type: bind
        source: C:/CellShuttle/docker-volumes/rabbitmq1/logs/
        target: /var/log/rabbitmq
    networks:
      shuttle-network:
        ipv4_address: 172.22.0.110
    healthcheck:
      test:
        - CMD
        - rabbitmq-diagnostics
        - check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 30
    logging:
      driver: json-file
      options:
        max-size: 15m
        max-file: "1"
    entrypoint: /etc/rabbitmq/cluster-entrypoint.sh
    depends_on: {}
  rabbitmq2:
    container_name: rabbitmq2
    hostname: rabbitmq2
    image: cellaresctmpcontainerregistry.azurecr.io/rabbitmq:3.12.12-management
    restart: unless-stopped
    ports:
      - 5674:5672
      - 15674:15672
    environment:
      TZ: America/Los_Angeles
      RABBITMQ_ERLANG_COOKIE: cellares-rabbitmq-cookie-shuttle
    dns:
      - 172.22.0.100
      - 1.1.1.1
    volumes:
      - type: bind
        source: C:/CellShuttle/docker-volumes/rabbitmq2/etc/
        target: /usr/local/etc/rabbitmq2
    networks:
      shuttle-network:
        ipv4_address: 172.22.0.111
    healthcheck:
      test:
        - CMD
        - rabbitmq-diagnostics
        - check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 30
    logging:
      driver: json-file
      options:
        max-size: 15m
        max-file: "1"
    entrypoint: /etc/rabbitmq/cluster-entrypoint.sh
    depends_on:
      rabbitmq1:
        condition: service_healthy
  rabbitmq3:
    container_name: rabbitmq3
    hostname: rabbitmq3
    image: cellaresctmpcontainerregistry.azurecr.io/rabbitmq:3.12.12-management
    restart: unless-stopped
    ports:
      - 5674:5672
      - 15674:15672
    environment:
      TZ: America/Los_Angeles
      RABBITMQ_ERLANG_COOKIE: cellares-rabbitmq-cookie-shuttle
    dns:
      - 172.22.0.100
      - 1.1.1.1
    volumes:
      - type: bind
        source: C:/CellShuttle/docker-volumes/rabbitmq3/etc/
        target: /usr/local/etc/rabbitmq3
    networks:
      shuttle-network:
        ipv4_address: 172.22.0.111
    healthcheck:
      test:
        - CMD
        - rabbitmq-diagnostics
        - check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 30
    logging:
      driver: json-file
      options:
        max-size: 15m
        max-file: "1"
    entrypoint: /etc/rabbitmq/cluster-entrypoint.sh
    depends_on:
      rabbitmq2:
        condition: service_healthy
networks:
  shuttle:
    name: shuttle
    external: true
