#@data/values-schema
#! This contains the value schema, shared values specifically for rabbitmq service  
---
#@overlay/match missing_ok=True
services:
  #@overlay/match missing_ok=True
  rabbitmq:
    image: mycompanyctmpcontainerregistry.azurecr.io/rabbitmq:3.12.12-management
    restart: unless-stopped
    healthcheck:
      #@schema/type any=True
      test:
        - CMD
        - rabbitmq-diagnostics
        - check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 30
    entrypoint: /etc/rabbitmq/cluster-entrypoint.sh


