#@ load("@ytt:data", "data")
#! This is the base template for docker-compose specific to local environment

version: #@ data.values.version

services:
  haproxy:
    container_name: #@ data.values.services.haproxy.container_name
    hostname: #@ data.values.services.haproxy.hostname
    image: #@ data.values.services.haproxy.image
    restart: #@ data.values.services.haproxy.restart
    ports: #@ data.values.services.haproxy.ports
    environment: #@ data.values.services.haproxy.environment
    dns: #@ data.values.dns
    volumes: #@ data.values.services.haproxy.volumes
    networks: #@ data.values.services.haproxy.networks
    healthcheck: #@ data.values.services.haproxy.healthcheck
    logging: #@ data.values.logging
    depends_on: #@ data.values.services.haproxy.depends_on
  rabbitmq1:
    container_name: #@ data.values.services.rabbitmq1.container_name
    hostname: #@ data.values.services.rabbitmq1.hostname
    image: #@ data.values.services.rabbitmq.image
    restart: #@ data.values.services.rabbitmq.restart
    ports: #@ data.values.services.rabbitmq1.ports
    environment: #@ data.values.services.rabbitmq1.environment
    dns: #@ data.values.dns
    volumes: #@ data.values.services.rabbitmq1.volumes
    networks: #@ data.values.services.rabbitmq1.networks
    healthcheck: #@ data.values.services.rabbitmq.healthcheck
    logging: #@ data.values.logging
    depends_on: #@ data.values.services.rabbitmq1.depends_on
    entrypoint: #@ data.values.services.rabbitmq.entrypoint
networks:
  shuttle:
    name: #@ data.values.networks.shuttle.name
    external: #@ data.values.networks.shuttle.external
