#@data/values-schema
#! This contains the value schema, values specifically for haproxy service in local environment
---
#@overlay/match missing_ok=True
services: 
  #@overlay/match missing_ok=True
  haproxy:
    #@overlay/match missing_ok=True
    depends_on:
      rabbitmq1:
        condition: service_healthy
