#@data/values-schema
#! This is the schema/defaults for docker-compose  
---
#@overlay/match missing_ok=True
services:
  #@overlay/match missing_ok=True
  haproxy:
    #@overlay/match missing_ok=True
    depends_on:
      rabbitmq3:
        condition: service_healthy
