#@data/values-schema
#! This contains the value schema, values specifically for haproxy service in shuttle environment
---
#@overlay/match missing_ok=True
services:
  #@overlay/match missing_ok=True
  haproxy:
    #@overlay/match missing_ok=True
    depends_on:
      rabbitmq3:
        condition: service_healthy
